name: docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@master

    - name: integration-test
      run: ./test/integration-test.sh

    - name: docker publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: minetestmail/mail
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
        cache: true
