name: jshint_backend

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: apt
      run: sudo apt-get install -y nodejs npm
    - name: install
      run: npm i
    - name: jshint
      run: npm run jshint_backend
